version: 2.1

jobs:
  build:
    docker:
      - image: cypress/base:14
    working_directory: /app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install NPM dependencies
          command: npm install --force
      - run:
          name: Install cypress
          command: npm install -g cypress

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run Cypress tests
          command:  npx cypress run --spec ./cypress/e2e/sequenced-tests.cy.js
